### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_cloudformation#1]
Hey @occurr, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are a major contributor to the CloudFormation service in ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by BadBastion** [comment]
Hey @benwilson512 ~ Yeah Kim (@bearleethere) and I are currently using EC2, ElastiCache, and CloudFormation for a project at Salesforce. You can add us as maintainers to any of those as we are already having to keep our local up to spec. 

Thanks! 
  - Daniel

**Comment by benwilson512** [comment]
Thanks! You both have been given write access to this repository.
