### ISSUE TITLE
Mention sweetxml in the docs

### ISSUE THREAD

**Issue by rikkus** [ex-aws/ex_aws_cloudformation#2]
The docs don't mention that you'll need sweetxml as a dependency if you want this to build with parsing support.

Maybe just add it as a dependency?

**Comment by benwilson512** [comment]
Not everyone wants to use SweetXml as the parser, there are several different XML parsers out there with various pros and cons. ExAws makes parsing pluggable, even when it ships with default parsing options built in.

A PR is welcome to make the note about SweetXML and built in parsing.
